# Generated by Django 5.0.6 on 2024-07-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='host_class_id',
            field=models.CharField(default=1, max_length=100, verbose_name='托管班ID'),
            preserve_default=False,
        ),
    ]
