# Generated by Django 5.0.6 on 2024-07-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0003_studentprofile_host_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('school', models.CharField(max_length=200, verbose_name='学校')),
                ('homeroom_teacher', models.CharField(max_length=100, verbose_name='班主任')),
                ('homeroom_teacher_phone', models.CharField(max_length=20, verbose_name='班主任联系方式')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级列表',
            },
        ),
        migrations.CreateModel(
            name='HostClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='托管班级名称')),
            ],
            options={
                'verbose_name': '托管班级',
                'verbose_name_plural': '托管班级列表',
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='homeroom_teacher',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='homeroom_teacher_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='host_class_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='school',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcwxapp.classroom', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='host_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcwxapp.hostclass', verbose_name='所在托管班级'),
        ),
    ]
