# Generated by Django 5.0.6 on 2024-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0004_classroom_hostclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('file_number', models.CharField(max_length=50, verbose_name='档案编号')),
                ('changed_hours', models.IntegerField(default=0, verbose_name='本次变化课时')),
                ('remaining_hours', models.IntegerField(default=0, verbose_name='剩余课时')),
                ('deducted_meal_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='本次扣减餐费')),
                ('meal_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='餐费余额')),
                ('occurrence_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('morning', models.BooleanField(default=False, verbose_name='上午')),
                ('afternoon', models.BooleanField(default=False, verbose_name='下午')),
                ('lunch', models.BooleanField(default=False, verbose_name='午饭')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '学生课时记录',
                'verbose_name_plural': '学生课时记录',
            },
        ),
    ]
