# Generated by Django 5.0.6 on 2024-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0005_studentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('file_number', models.CharField(max_length=50, verbose_name='档案编号')),
                ('recharge_date', models.DateField(verbose_name='充值日期')),
                ('recharge_hours', models.IntegerField(default=0, verbose_name='充值课时')),
                ('recharge_meal_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='充值餐费')),
                ('payment_method', models.CharField(choices=[('wechat', '微信'), ('transfer', '转账'), ('cash', '现金'), ('other', '其他')], default='other', max_length=10, verbose_name='缴费方式')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='meal_balance',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='paid_classes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='remaining_classes',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='remaining_points',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_classes',
        ),
    ]
