# Generated by Django 5.0.6 on 2024-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0006_rechargerecord_remove_studentprofile_meal_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='meal_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='餐费余额'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='remaining_hours',
            field=models.IntegerField(default=0, verbose_name='剩余课时'),
        ),
    ]
