# Generated by Django 5.0.6 on 2024-07-12 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0007_studentprofile_meal_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='oc_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间'),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='occurrence_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
    ]
