# Generated by Django 5.0.6 on 2024-07-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0008_studentrecord_oc_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='标签'),
        ),
    ]
