# Generated by Django 5.0.6 on 2024-07-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcwxapp', '0009_studentrecord_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargerecord',
            name='payment_method',
            field=models.CharField(default='其他', max_length=10, verbose_name='缴费方式'),
        ),
    ]
